### ISSUE TITLE
Review U1 Modeling Language

### ISSUE THREAD

**Issue by maryfries** [bjc-edc-2017-18/bjc-r#22]
"New" FP content based on older cut content (formerly emailed to you as 1.2.5)

Probably needs only light review and your thoughts on placement.

http://localhost/bjc-r/cur/programming/1-introduction/2-gossip-and-greet/old/5-sentence-builder.html

**Comment by brianharvey** [comment]
TIF A can't be done either, before IF.  Maybe move this page to 2.2.3?

**Comment by maryfries** [comment]
@brianharvey  Since we are bringing back [more complicated who](http://localhost/bjc-r/cur/programming/2-complexity/old/new/3-if-else.html) now as 1.2.4, this should be ok now right?

**Comment by maryfries** [comment]
@EPaulG this is another FP-inspired page for you to review. You probably wrote the original back in the day. ;) I'm proposing it for a U1 optional project, though I'm less attached to that than the placement of the math tools projects in U2 and U3. I suppose it could also go after more complicated who as 1.2.5, but that would make for yet another required page. Thoughts?

**Comment by brianharvey** [comment]
I still think the "complex sentence" reporter needs a different name.

**Comment by maryfries** [comment]
@brianharvey any suggestions?

**Comment by maryfries** [comment]
Paul reviewed [4/24/19](https://github.com/bjc-edc-2017-18/bjc-r/commit/5f1b580fd5a4783b90ae73687b56103033f91b8d)
