### ISSUE TITLE
Review Revised Automated Fortune Teller (U2 OP #1)

### ISSUE THREAD

**Issue by maryfries** [bjc-edc-2017-18/bjc-r#23]
I've just made some changes to the existing project and am announcing them for transparency and a second pair of eyes.

Please review and then remove/respond to my comments as you go. Thanks!

http://localhost/bjc-r/cur/programming/2-complexity/optional-projects/1-magic8ball.html

**Comment by brianharvey** [comment]
Oy.  I just tried syncing my edits, and not only did I get conflicts on that page, I also got two other pages that I had allegedly changed.  Now I'm scared to commit again.

I agreed with your comments.  I changed the TIF to an ITIT, which is what those problems are--lots of time, no particular depth.  And I flushed the vague. Selim-like "do a whole different project" TIF.

Still needs work:  Unlike what the text and video say, you don't have to switch to costumes/sounds tab before dragging in pictures/sounds, and you don't have to drop them on the middle area.  You can drop them anywhere in the Snap<i>!</i> window.

**Comment by brianharvey** [comment]
I got myself straightened out.  I did disagree about the names of colors; the point of ADA is to make things better for the disabled, not worse for the abled.  This has been bugging me for a while and we should talk about it at a meeting.

**Comment by maryfries** [comment]
I emailed you about these concerns, made some light changes, and synced.
