### ISSUE TITLE
U3 Optional Projects Animation Studio ADA Fixes

### ISSUE THREAD

**Issue by lmock** [bjc-edc-2017-18/bjc-r#6]
https://github.com/bjc-edc-2017-18/bjc-r/blob/d775c061e483bb8c43374a4e0aea2844c899b063/cur/programming/3-lists/optional-projects/1-animation-studio.html

`<img class="indent" data-gifffer="/bjc-r/img/3-lists/AnimationStudio_img/UFO.gif" height="350" alt="Animating a UFO" title="Animating a UFO"/>
`

Alt text of animation is not descriptive.  Because it is an important part of the assignment, provide more descriptive alternative text, or describe it in the paragraph before the image.

**Comment by stezel** [comment]
Great directions for improvement thank you!
