### ISSUE TITLE
U3 Optional Projects Op Art ADA Fixes

### ISSUE THREAD

**Issue by lmock** [bjc-edc-2017-18/bjc-r#7]
https://github.com/bjc-edc-2017-18/bjc-r/blob/d775c061e483bb8c43374a4e0aea2844c899b063/cur/programming/3-lists/optional-projects/2-op-art.html

`<img class="indent" data-gifffer="/bjc-r/img/3-lists/OpArt_img/OpArtAnimation.gif"  height="300" alt="Op Art animation" title="Op Art animation" /></li>
`

Alt text of animation is not descriptive.  Because it is an important part of the assignment, provide more descriptive alternative text, or describe it in the paragraph before the image.

**Comment by stezel** [comment]
Great suggestions, thank you!
