### ISSUE TITLE
U3 Optional Projects Music Project ADA Fixes

### ISSUE THREAD

**Issue by lmock** [bjc-edc-2017-18/bjc-r#8]
https://github.com/bjc-edc-2017-18/bjc-r/blob/d775c061e483bb8c43374a4e0aea2844c899b063/cur/programming/3-lists/optional-projects/3-music-project.html

Line 91
`<a href="#hint-target" data-toggle="collapse">Click here for a chart for note pitch numbers. </a>
`

Line 127
`<a href="#hint-target-2" data-toggle="collapse">Click here if you need a hint.</a>
`

Avoid using “Click here…” in links.

**Comment by maryfries** [comment]
We don't know how better to handle this for the hints. Can you offer some suggestions? Could "See a chart for note pitch numbers" work for the first one? What about the second one?

**Comment by lmock** [comment]
Maybe you could try "Reveal a hint"?
